name: lg_controller
description: Controller application for the LG Screen.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  page_transition: ^2.0.9
  equatable: ^2.0.5
  shared_preferences: ^2.0.18
  googleapis: 'any'
  googleapis_auth: '^1.3.1'
  path_provider: '^2.0.13'
  sqflite: '^2.2.5'
  google_maps_flutter: ^2.2.5
  flutter_google_places: '^0.3.0'
  cached_network_image: '^3.2.3'
  toast: ^0.3.0
  url_launcher: ^6.1.10
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^0.8.6+4
  get_ip_address: ^0.0.5 
  barcode_scan2: ^4.2.4
  dart_ipify: ^1.1.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_launcher_icons: "^0.12.0"

dev_dependencies:
  mockito: '5.3.2'
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


flutter_icons:
  image_path: "image_assets/AppLogo.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - image_assets/


